### PR TITLE
Update to upstream master + override-keywords-fix

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
I'll just say that personally I would prefer we use a branch when adding commits on top, rather than later having to force-push into master - but we have an history of making commits to master on ArduPilot submodules.

**Comment by peterbarker** [comment]
@OXINARF are you suggesting something like an ardupilot-master branch?

**Comment by OXINARF** [comment]
@peterbarker Something like that, yes. In my opinion master branch should track upstream. This isn't a blocker here though, as I said, we usually use master to push our own commits and then force-push into it.

**Comment by peterbarker** [comment]
On Tue, 20 Aug 2019, Francisco Ferreira wrote:

> @peterbarker Something like that, yes. In my opinion master branch should track upstream. This isn't a blocker here though, as I said, we usually use
> master to push our own commits and then force-push into it.

OK, I propose we move to this model.  Currently our master doesn't point 
to upstream master - it points to a tag coming off upstream master's 
history.

That's a separate mess I'd like to leave alone at the moment.

I propose I push up a new branch, ardupilot-master, and make sure my 
commit which references the new commit in modules/gtest is still valid.

We change the "default branch" for our googletest repository to 
ardupilot-master

At some stage in the future we reset our googletest repository master to 
point to upstream master.

Does that seem reasonable?

**Comment by OXINARF** [comment]
Good to me.

I would just advise that we create **now** a tag (something like `ardupilot-20190821`) that points at the currently used commit - reason being that when we reset our googletest repository master to point to upstream, we are likely to forget doing this and then going back can leave you with an unreachable submodule commit.

**Comment by peterbarker** [comment]
I've created a `ardupilot-20190924` tag.

**Comment by peterbarker** [comment]
I've pushed an `ardupilot-master` branch into our googletest repository - it's up-to-date upstream master with the suggest-overrides fix on top.  I've also force-pushed the PR against `ardupilot/ardupilot` referencing that commit.

**Comment by peterbarker** [comment]
This should no longer be merged.

I've PR'd our changes against upstream.

If they're merged, we'll grab the new upstream master and update our master to that (and start to reference that in our `ardupilot/ardupilot` submodule (remembering to create an `ardupilot-master-2019xxxx` tag!)

**Comment by peterbarker** [comment]
I've created an `ardupilot-20200125` tag to point to our current master

**Comment by peterbarker** [comment]
I've done as suggested in this PR; we're now running a much more recent version of gtest which incorporates the local changes we were running.

**Pull request closed without merging**
